server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: root
applications:
  product:
    url: "http://localhost:8082/api/v1"
  userbank:
    url: "http://localhost:8081/api/v1"
logging:
  level:
    com.shamiyana.order.client: DEBUG
    org.springframework.cloud.openfeign: DEBUG
bank:
  id: 7
feign:
  client:
    config:
      default:
        connectTimeout: 5000     # time to establish connection
        readTimeout: 10000       # time to wait for response
        loggerLevel: FULL
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}